////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

The default renderers for XML and JSON can be found in the `grails.rest.render.xml` and `grails.rest.render.json` packages respectively. These use the Grails converters (`grails.converters.XML` and `grails.converters.JSON`) by default for response rendering. 

You can easily customize response rendering using these default renderers. A common change you may want to make is to include or exclude certain properties from rendering. 


==== Including or Excluding Properties from Rendering


As mentioned previously, Grails maintains a registry of `grails.rest.render.Renderer` instances. There are some default configured renderers and the ability to register or override renderers for a given domain class or even for a collection of domain classes. To include a particular property from rendering you need to register a custom renderer by defining a bean in `grails-app/conf/spring/resources.groovy`:

[source,groovy]
----
import grails.rest.render.xml.*

beans = {
    bookRenderer(XmlRenderer, Book) {
        includes = ['title']
    }
}
----


NOTE: The bean name is not important (Grails will scan the application context for all registered renderer beans), but for organizational and readability purposes it is recommended you name it something meaningful.

To exclude a property, the `excludes` property of the `XmlRenderer` class can be used:

[source,groovy]
----
import grails.rest.render.xml.*

beans = {
    bookRenderer(XmlRenderer, Book) {
        excludes = ['isbn']
    }
}
----


==== Customizing the Converters


As mentioned previously, the default renders use the `grails.converters` package under the covers. In other words, under the covers they essentially do the following:

[source,groovy]
----
import grails.converters.*

...
render book as XML

// or render book as JSON
----

Why the separation between converters and renderers? Well a renderer has more flexibility to use whatever rendering technology you chose. When implementing a custom renderer you could use https://github.com/FasterXML/jackson/[Jackson], https://github.com/google/gson[Google Gson] or any Java library to implement the renderer. Converters on the other hand are very much tied to Grails' own marshalling implementation.


==== Date and Time Rendering


The JSON converter renders date and time values the same way as Spring Boot's default Jackson `JsonMapper`, so a Grails
application and a Spring Boot application return the same JSON for the same values:

[cols="2,3", options="header"]
|===
| Type
| Rendered as

| `java.util.Date`, `java.sql.Date`, `java.sql.Timestamp`, `Calendar`, `XMLGregorianCalendar`
| a UTC instant with millisecond precision, such as `"2025-10-08T07:48:46.407Z"`

| `java.sql.Time`
| its wall-clock time in the JVM default time zone, such as `"01:48:46"`

| `Instant`
| ISO-8601, such as `"2025-10-08T07:48:46.407254Z"`

| `LocalDate`, `LocalTime`, `LocalDateTime`
| ISO-8601 without a time zone, such as `"2025-10-08"`, `"01:48:46.407254"`, `"2025-10-08T01:48:46.407254"`

| `OffsetDateTime`, `ZonedDateTime`, `OffsetTime`
| ISO-8601 with the offset and without a zone ID, such as `"2025-10-08T01:48:46.407254-06:00"`, `"03:00-03:00"`

| `YearMonth`, `MonthDay`, `Duration`, `Period`, `javax.xml.datatype.Duration`
| ISO-8601, such as `"2026-09"`, `"--09-25"`, `"PT1H30M"`, `"P1Y2M3D"`, `"P1DT2H"`

| `Year`, `Month`
| a number, such as `2026`, or `9` for September

| `ZoneId`, `ZoneOffset`, `TimeZone`
| the ID, such as `"America/Sao_Paulo"` or `"-03:00"`
|===

A map keyed by `Date`, `Calendar` or `ZonedDateTime` values renders its keys the same way as those values; other map
keys render with their `toString()`. JSON views render dates and times the same way, and data binding binds a `Month`
back from its number.

Setting `grails.converters.json.date` to `javascript` renders `java.util.Date` values as JavaScript `new Date(...)`
constructors instead. To render a type differently, register an object marshaller for it, for example in `BootStrap.init`:

[source,groovy]
----
JSON.registerObjectMarshaller(Month) { Month month ->
    month.name()
}
----
