////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

The default renderers for XML and JSON can be found in the `grails.rest.render.xml` and `grails.rest.render.json` packages respectively. These use the Grails converters (`grails.converters.XML` and `grails.converters.JSON`) by default for response rendering. 

You can easily customize response rendering using these default renderers. A common change you may want to make is to include or exclude certain properties from rendering. 


==== Including or Excluding Properties from Rendering


As mentioned previously, Grails maintains a registry of `grails.rest.render.Renderer` instances. There are some default configured renderers and the ability to register or override renderers for a given domain class or even for a collection of domain classes. To include a particular property from rendering you need to register a custom renderer by defining a bean in `grails-app/conf/spring/resources.groovy`:

[source,groovy]
----
import grails.rest.render.xml.*

beans = {
    bookRenderer(XmlRenderer, Book) {
        includes = ['title']
    }
}
----


NOTE: The bean name is not important (Grails will scan the application context for all registered renderer beans), but for organizational and readability purposes it is recommended you name it something meaningful.

To exclude a property, the `excludes` property of the `XmlRenderer` class can be used:

[source,groovy]
----
import grails.rest.render.xml.*

beans = {
    bookRenderer(XmlRenderer, Book) {
        excludes = ['isbn']
    }
}
----


==== Customizing the Converters


As mentioned previously, the default renders use the `grails.converters` package under the covers. In other words, under the covers they essentially do the following:

[source,groovy]
----
import grails.converters.*

...
render book as XML

// or render book as JSON
----

Why the separation between converters and renderers? Well a renderer has more flexibility to use whatever rendering technology you chose. When implementing a custom renderer you could use https://github.com/FasterXML/jackson/[Jackson], https://github.com/google/gson[Google Gson] or any Java library to implement the renderer. Converters on the other hand use Grails' object marshallers, and write JSON through the application's Jackson `JsonMapper`, as described below.


==== JSON Rendering With Spring Boot's JsonMapper


The JSON converter writes JSON through the application's Jackson `JsonMapper`, the one Spring Boot auto-configures, so a
Grails application and a Spring Boot application return the same JSON for the same values. The mapper writes every
single value it has a dedicated serializer for, such as dates and times, `Month`, `UUID`, `Locale`, `byte[]`, types with
a `@JsonValue` and the types of Jackson modules registered with the application, and it formats and pretty prints the
JSON text. `spring.jackson.*` properties therefore configure `render ... as JSON` as well:

[source,yaml]
----
spring:
    jackson:
        time-zone: America/New_York
----

Domain classes, beans, enums, records, `Optional`, collections and maps are rendered by Grails marshallers, and the
values they contain as any other value is. Enums render by `name()`, so that the JSON binds back to them, and strings are
escaped for an HTML `<script>` element (`</` is written as `<\u002f`). To render a type differently, register an object
marshaller for it, which takes precedence over the mapper, for example in `BootStrap.init`:

[source,groovy]
----
JSON.registerObjectMarshaller(Date) { Date date ->
    date.time
}
----

Setting `grails.converters.json.date` to `javascript` renders `java.util.Date` values as JavaScript `new Date(...)`
constructors instead.
