////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Since Grails 2.3, it possible to create RESTful URL mappings that map onto controllers by convention. The syntax to do so is as follows:

[source,groovy]
----
"/books"(resources:'book')
----

You define a base URI and the name of the controller to map to using the `resources` parameter. The above mapping will result in the following URLs:


[format="csv", options="header"]
|===

HTTP Method,URI,Grails Action
GET,/books,index
GET,/books/create,create
POST,/books,save
GET,/books/${id},show
GET,/books/${id}/edit,edit
PUT,/books/${id},update
PATCH,/books/${id},patch
DELETE,/books/${id},delete
|===

If you are not sure which mapping will be generated for your case just run the command `url-mappings-report` in your grails console. It will give you a really neat report for all the url mappings.

If you wish to include or exclude any of the generated URL mappings you can do so with the `includes` or `excludes` parameter, which accepts the name of the Grails action to include or exclude:

[source,groovy]
----
"/books"(resources:'book', excludes:['delete', 'update'])

or 

"/books"(resources:'book', includes:['index', 'show'])
----


==== Explicit REST Mappings


As of Grails 3.1, if you prefer not to rely on a `resources` mapping to define your mappings then you can prefix any URL mapping with the HTTP method name (in lower case) to indicate the HTTP method it applies to. The following URL mapping:

[source,groovy]
----
"/books"(resources:'book')
----

Is equivalent to:

[source,groovy]
----
get "/books"(controller:"book", action:"index")
get "/books/create"(controller:"book", action:"create")
post "/books"(controller:"book", action:"save")
get "/books/$id"(controller:"book", action:"show")
get "/books/$id/edit"(controller:"book", action:"edit")
put "/books/$id"(controller:"book", action:"update")
patch "/books/$id"(controller:"book", action:"patch")
delete "/books/$id"(controller:"book", action:"delete")
----

Notice how the HTTP method name is prefixed prior to each URL mapping definition.


==== Mapping every controller as a resource


If every controller in an application follows the RESTful resource conventions, the mappings can be
applied to all of them at once by capturing the controller in the URL and passing `*` as the
`resources` argument:

[source,groovy]
----
"/$controller"(resources: '*')
----

This generates the same mappings as a named `resources` mapping, but resolves the controller from the
request instead of from the mapping, so the number of mappings does not grow with the number of
controllers:

[format="csv", options="header"]
|===

HTTP Method,URI,Grails Action
GET,/${controller},index
GET,/${controller}/create,create
POST,/${controller},save
GET,/${controller}/${id},show
GET,/${controller}/${id}/edit,edit
PUT,/${controller}/${id},update
PATCH,/${controller}/${id},patch
DELETE,/${controller}/${id},delete
|===

Because the controller and action are captured from the URL, they are subject to the same validation
as any other wildcard mapping, described in link:theWebLayer.html#embeddedVariables[Embedded Variables]:
a URI whose captured values do not correspond to a registered controller and action does not match.

The `includes` and `excludes` parameters apply as they do for a named resource. An application that
serves only JSON, for example, has no use for the two actions that render HTML forms:

[source,groovy]
----
"/$controller"(resources: '*', excludes: ['create', 'edit'])
----

The mapping can also be placed inside a `group`:

[source,groovy]
----
group "/api/v1", {
    "/$controller"(resources: '*')
}
----

A namespace can be captured from the URL in the same way, which maps every namespaced controller
without naming the namespaces:

[source,groovy]
----
"/$namespace/$controller"(resources: '*')
----

[format="csv", options="header"]
|===

HTTP Method,URI,Grails Action
GET,/${namespace}/${controller},index
GET,/${namespace}/${controller}/${id},show
|===

NOTE: The URL must capture the controller, and child resources cannot be nested within a wildcard
`resources` mapping, because the controller is not known until a request is matched. Both are
rejected when the mappings are evaluated.


==== Single resources


A single resource is a resource for which there is only one (possibly per user) in the system. You can create a single resource using the `single` parameter (as opposed to `resources`):

[source,groovy]
----
"/book"(single:'book')
----

This results in the following URL mappings:

[format="csv", options="header"]
|===

HTTP Method,URI,Grails Action
GET,/book/create,create
POST,/book,save
GET,/book,show
GET,/book/edit,edit
PUT,/book,update
PATCH,/book,patch
DELETE,/book,delete
|===

The main difference is that the id is not included in the URL mapping.


==== Nested Resources


You can nest resource mappings to generate child resources. For example:

[source,groovy]
----
"/books"(resources:'book') {
  "/authors"(resources:"author")
}
----

The above will result in the following URL mappings:

[format="csv", options="header"]
|===

HTTP Method,URL,Grails Action
GET,/books/${bookId}/authors,index
GET,/books/${bookId}/authors/create,create
POST,/books/${bookId}/authors,save
GET,/books/${bookId}/authors/${id},show
GET,/books/${bookId}/authors/${id}/edit,edit
PUT,/books/${bookId}/authors/${id},update
PATCH,/books/${bookId}/authors/${id},patch
DELETE,/books/${bookId}/authors/${id},delete
|===

You can also nest regular URL mappings within a resource mapping:

[source,groovy]
----
"/books"(resources: "book") {
    "/publisher"(controller:"publisher")
}
----

This will result in the following URL being available:

[format="csv", options="header"]
|===

HTTP Method,URL,Grails Action
GET,/books/${bookId}/publisher,index
|===

To map a URI directly below a resource then use a collection block:

[source,groovy]
----
"/books"(resources: "book") {
    collection {
        "/publisher"(controller:"publisher")    
    }    
}
----

This will result in the following URL being available (without the ID):

[format="csv", options="header"]
|===

HTTP Method,URL,Grails Action
GET,/books/publisher,index
|===


==== Linking to RESTful Mappings


You can link to any URL mapping created with the `g:link` tag provided by Grails simply by referencing the controller and action to link to:

[source,groovy]
----
<g:link controller="book" action="index">My Link</g:link>
----

As a convenience you can also pass a domain instance to the `resource` attribute of the `link` tag:

[source,groovy]
----
<g:link resource="${book}">My Link</g:link>
----

This will automatically produce the correct link (in this case "/books/1" for an id of "1").


The case of nested resources is a little different as they typically required two identifiers (the id of the resource and the one it is nested within). For example given the nested resources:

[source,groovy]
----
"/books"(resources:'book') {
  "/authors"(resources:"author")
}
----

If you wished to link to the `show` action of the `author` controller, you would write:

[source,groovy]
----
// Results in /books/1/authors/2
<g:link controller="author" action="show" method="GET" params="[bookId:1]" id="2">The Author</g:link>
----

However, to make this more concise there is a `resource` attribute to the link tag which can be used instead:

[source,groovy]
----
// Results in /books/1/authors/2
<g:link resource="book/author" action="show" bookId="1" id="2">My Link</g:link>
----

The resource attribute accepts a path to the resource separated by a slash (in this case "book/author"). The attributes of the tag can be used to specify the necessary `bookId` parameter.
