////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

The `link` tag offers an easy way to link to any domain class resource:

[source,xml]
----
<g:link resource="${book}">My Link</g:link>
----

However, currently you cannot use g:link to link to the DELETE action and most browsers do not support sending the DELETE method directly.

The best way to accomplish this is to use a form submit:

[source,xml]
----
<form action="/book/2" method="post">
 	<input type="hidden" name="_method" value="DELETE"/>
</form>
----

Grails supports overriding the request method via the hidden `_method` parameter. This is for browser compatibility purposes. This is useful when using restful resource mappings to create powerful web interfaces.
To make a link fire this type of event, perhaps capture all click events for links with a `data-method` attribute and issue a form submit via JavaScript.

The same override can be requested with an `X-HTTP-Method-Override` header only while the hidden HTTP method
filter is enabled; it is disabled by default as of Grails 8.

By default the `_method` parameter is resolved inside the dispatcher, after multipart handling and after the
servlet filter chain. `<g:form>` emits the parameter as it always has. A `resources` mapping additionally routes
a `POST` to the member URL at the `update` action, so a client that cannot send the parameter -- an AngularJS
`$resource` and the clients modelled on it POST to save an existing object -- reaches `update` without it.

The previous behaviour -- a servlet filter rewriting the request method ahead of the dispatcher -- can be
restored:

[source,yaml]
.grails-app/conf/application.yml
----
grails:
    web:
        hiddenmethod:
            filter:
                enabled: true
----

WARNING: With the filter disabled, servlet filters and the Spring Security filter chain see the request's real
`POST` method, and the URL does not distinguish `update` from `delete`. Authorization rules keyed on the HTTP
method must be reviewed.
