////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

include::ui/introduction.adoc[leveloffset=+1]

include::ui/user.adoc[leveloffset=+1]

include::ui/role.adoc[leveloffset=+1]

include::ui/requestmap.adoc[leveloffset=+1]

include::ui/userRegistration.adoc[leveloffset=+1]

include::ui/forgotPassword.adoc[leveloffset=+1]

include::ui/acls.adoc[leveloffset=+1]

include::ui/persistentCookie.adoc[leveloffset=+1]

include::ui/configUI.adoc[leveloffset=+1]

include::ui/customization.adoc[leveloffset=+1]

include::ui/scripts.adoc[leveloffset=+1]

== API Reference

The UI plugin Groovydoc API documentation for historical (pre-merge) releases is available at the link:{grailsSpringSecurityLegacyDocs}/ui-plugin/groovydoc/index.html[legacy Spring Security UI plugin API reference].
