////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== stop-app



=== Purpose


Stops a Grails application that was started with the link:{commandLineRef}run-app.html[run-app] command in the same interactive CLI session.

NOTE: This command works in development mode only and must be run from the same interactive `grails` session that started the application with `run-app`.


=== Examples


[source,groovy]
----
$ grails
grails> run-app
grails> stop-app
----


=== Description


When an application is started with `run-app` in the interactive Grails shell, the application runs as an asynchronous Gradle `bootRun` build. The `stop-app` command cancels that build, which shuts down the running application without exiting the CLI. A subsequent `run-app` can then start the application again.

This is a CLI only mechanism: it does not require the Spring Boot Actuator shutdown endpoint to be enabled, nor does it rely on JMX.

If no application started by `run-app` is running in the current session, `stop-app` reports that the application is not running.
