////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Grails is no more or less secure than Java Servlets. However, Java servlets (and hence Grails) are extremely secure and largely immune to common buffer overrun and malformed URL exploits due to the nature of the Java Virtual Machine underpinning the code.

Web security problems typically occur due to developer naivety or mistakes, and there is a little Grails can do to avoid common mistakes and make writing secure applications easier to write.


==== What Grails Automatically Does


Grails has a few built in safety mechanisms by default.

* All standard database access via link:GORM.html[GORM] domain objects is automatically SQL escaped to prevent SQL injection attacks
* The default link:scaffolding.html[scaffolding] templates HTML escape all data fields when displayed
* Grails link creating tags (link:{gspTagsRef}link.html[link], link:{gspTagsRef}form.html[form], link:{gspTagsRef}createLink.html[createLink], link:{gspTagsRef}createLinkTo.html[createLinkTo] and others) all use appropriate escaping mechanisms to prevent code injection
* Grails provides <<codecs,codecs>> to let you trivially escape data when rendered as HTML, JavaScript and URLs to prevent injection attacks here.

==== HTTP Security Headers

Grails servlet web applications send a small set of browser hardening headers by default:

[cols="1,1", options="header"]
|===
| Header
| Default value

| `X-Content-Type-Options`
| `nosniff`

| `X-Frame-Options`
| `SAMEORIGIN`

| `Referrer-Policy`
| `strict-origin-when-cross-origin`

| `X-XSS-Protection`
| `0`
|===

HSTS and Content Security Policy are not enabled by default because their correct values depend on deployment topology and application assets.
When HSTS is enabled, Grails sends `Strict-Transport-Security` only for secure requests.

You can disable the whole filter, disable individual headers, or override values from `application.yml`:

[source,yaml]
.grails-app/conf/application.yml
----
grails:
    security:
        headers:
            enabled: true
            frame-options:
                value: DENY
            referrer-policy:
                value: no-referrer-when-downgrade
            hsts:
                enabled: true
                value: max-age=31536000; includeSubDomains
            content-security-policy:
                enabled: true
                value: default-src 'self'
----

Set `grails.security.headers.<header>.enabled` to `false` to omit a single header.
For example, `grails.security.headers.xss-protection.enabled: false` omits `X-XSS-Protection`.
If an application or another filter has already set one of these headers on the response, Grails leaves that value unchanged.
