import org.gradle.api.tasks.compile.GroovyCompile

plugins {
    id 'org.apache.grails.gradle.grails-plugin'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.0.7'
}

grails {
    bom = null
    cliAutoProvision = false
    starImports = ['java.time']
}

tasks.withType(GroovyCompile).configureEach {
    groovyOptions.configurationScript = file('cfg.groovy')
}

tasks.register('compileAdHocGroovy', GroovyCompile) {
    source = fileTree('src/ad-hoc/groovy')
    classpath = configurations.compileClasspath
    destinationDirectory = layout.buildDirectory.dir('classes/groovy/ad-hoc')
}

gradle.projectsEvaluated {
    tasks.register('compileLateGroovy', GroovyCompile) {
        source = fileTree('src/late/groovy')
        classpath = configurations.compileClasspath
        destinationDirectory = layout.buildDirectory.dir('classes/groovy/late')
    }
}
