grails-geb=5.0.0-SNAPSHOT
grails-data-hibernate5-dbmigration=9.0.0-SNAPSHOT
grails-data-hibernate5=9.0.0-SNAPSHOT
grails-data-mongodb=9.0.0-SNAPSHOT
grails-data-mongodb-gson-templates=9.0.0-SNAPSHOT
grails-fields=7.0.0-SNAPSHOT
grails-scaffolding=7.0.0-SNAPSHOT
grails-json=7.0.0-SNAPSHOT
grails-markup=7.0.0-SNAPSHOT