////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== findWhere



=== Purpose


Uses named arguments corresponding to domain class property names to execute a query returning the first matching result.


=== Examples


Given the domain class:

[source,groovy]
----
class Book {

   String title
   Date releaseDate
   String author

   static constraints = {
      releaseDate nullable: true
   }
}
----

You can query in the form:

[source,groovy]
----
def book = Book.findWhere(author: "Stephen King", title: "The Stand")

boolean isReleased = Book.findWhere(author: "Stephen King",
                                    title: "The Stand",
                                    releaseDate: null) != null
----


=== Description


`findWhere` returns the first matching instance, or `null` when no instance matches. A `null` value in the argument map matches rows where that property is `null`.

Only domain class property names may be used as keys in the argument map. Invalid property names are rejected instead of being interpolated into the generated query.

Parameters:

* `queryParams` - A `Map` of key/value pairs to be used in the query
* `args` - Optional query arguments such as `offset`, `cache`, `readOnly`, `fetchSize`, `timeout`, `flushMode`, and `lock`. `findWhere` always limits the query to one result.
