<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->
[[advancedGORMFeatures-ormdsl]]
== ORM DSL

The ORM DSL is a `static mapping` closure on every domain class that gives you fine-grained control over how GORM maps your domain model to the database schema.

See the subsections below for details on each feature:

* xref:ormdsl-tableAndColumnNames[Table and Column Names]
* xref:ormdsl-identity[Identity]
* xref:ormdsl-compositePrimaryKeys[Composite Primary Keys]
* xref:ormdsl-optimisticLockingAndVersioning[Optimistic Locking and Versioning]
* xref:ormdsl-inheritanceStrategies[Inheritance Strategies]
* xref:ormdsl-fetchingDSL[Fetching Strategies]
* xref:ormdsl-caching[Caching]
* xref:ormdsl-customCascadeBehaviour[Custom Cascade Behaviour]
* xref:ormdsl-customNamingStrategy[Custom Naming Strategy]
* xref:ormdsl-customHibernateTypes[Custom Hibernate Types]
* xref:ormdsl-derivedProperties[Derived Properties]
* xref:ormdsl-databaseIndices[Database Indices]
