////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////



=== "grails run-app"


You should be very familiar with this approach by now, since it is the most common method of running an application during the development phase. An embedded Tomcat server is launched that loads the web application from the development sources, thus allowing it to pick up any changes to application files.

You can run the application in the production environment using:

[source,groovy]
----
grails prod run-app
----

You can run the app using the `bootRun` Gradle task. The next command uses the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper].

`./gradlew bootRun`

You can specify an environment supplying `grails.env` system property.

`./gradlew -Dgrails.env=prod bootRun`

=== Runnable WAR or JAR file

Another way to deploy in Grails 3.0 or above is to use the new support for runnable JAR or WAR files. To create runnable archives, run `grails package`:

[source,xml]
----
grails package
----

Alternatively, you could use the `assemble` Gradle task.

`./gradlew assemble`

You can then run either the WAR file or the JAR using your Java installation:

[source,groovy]
----
java -Dgrails.env=prod -jar build/libs/mywar-0.1.war    (or .jar)
----

=== A TAR/ZIP distribution

WARNING: Note: TAR/ZIP distribution assembly has been removed from Grails 3.1.


=== Advanced Container Deployment with Layered Builds

For production deployments in containerized environments, Grails applications can leverage Spring Boot's layered JAR functionality. This approach separates the application into distinct layers (dependencies, snapshots, and application code), optimizing Docker image builds and storage.

==== Creating Layered JARs

To create a layered executable JAR, configure your `build.gradle`:

[source,gradle]
----
bootJar {
    enabled = true
    archiveClassifier = 'exec'
    layered {
        enabled = true
    }
}

jar {
    enabled = true
    archiveClassifier = 'plain'
}
----

==== Building Optimized Docker Images

Once you have a layered JAR, you can create an optimized Docker image using the extracted layers:

[source,Dockerfile]
----
FROM eclipse-temurin:17-jre-jammy

VOLUME /tmp

ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","example.Application"]
----

To prepare the layers for Docker:

[source,bash]
----
grails package
java -Djarmode=layertools -jar build/libs/myapp-*-exec.jar extract
----

==== Benefits of Layered Builds

* **Reduced image sizes**: Only changed layers need to be rebuilt
* **Faster deployments**: Docker layer caching improves build times
* **Optimized storage**: Shared layers across applications reduce total storage requirements

==== Production Deployment Commands

For production deployments, consider using these optimized approaches:

[source,bash]
----
# Create layered JAR for container deployment
grails package

# Run with specific memory settings
java -server -Xmx768M -Dgrails.env=prod -jar build/libs/myapp-*-exec.jar

# Or with specific JVM options for container environments
java -XX:+UseContainerSupport \
     -XX:MaxRAMPercentage=75.0 \
     -Dgrails.env=prod \
     -jar build/libs/myapp-*-exec.jar
----

=== "./gradlew bootRun"


You should be very familiar with this approach by now, since it is the most common method of running an application during the development phase. An embedded Tomcat server is launched that loads the web application from the development sources, thus allowing it to pick up any changes to application files.

You can run the application in the production environment using:

[source,groovy]
----
./gradlew bootRun -Dgrails.env=prod
----

You can run the app using the `bootRun` Gradle task. The next command uses the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper].

`./gradlew bootRun`

You can specify an environment supplying `grails.env` system property. 

`./gradlew -Dgrails.env=prod bootRun`

=== Runnable WAR or JAR file

Another way to deploy in Grails 3.0 or above is to use the new support for runnable JAR or WAR files. To create runnable archives, run `grails package`:

[source,xml]
----
grails package
----

Alternatively, you could use the `assemble` Gradle task.

`./gradlew assemble`

You can then run either the WAR file or the JAR using your Java installation:

[source,groovy]
----
java -Dgrails.env=prod -jar build/libs/mywar-0.1.war    (or .jar)
----

=== A TAR/ZIP distribution

WARNING: Note: TAR/ZIP distribution assembly has been removed from Grails 3.1.
