////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[persistenceBasics-modificationChecking]]
== Modification Checking

Hibernate tracks which properties have been modified since the entity was loaded. GORM exposes this via `isDirty()` and related methods.

=== Checking if an Instance is Dirty

[source,groovy]
----
def book = Book.get(1)
book.isDirty()      // false — just loaded

book.title = 'New Title'
book.isDirty()      // true — title has changed
----

=== Checking a Specific Property

[source,groovy]
----
book.isDirty('title')   // true
book.isDirty('genre')   // false — genre unchanged
----

=== Getting the Original Value

[source,groovy]
----
def book = Book.get(1)
println book.title          // 'Original Title'
book.title = 'New Title'
println book.getPersistentValue('title')    // 'Original Title'
----

=== Dirty Properties

Get a list of all property names that have changed:

[source,groovy]
----
def book = Book.get(1)
book.title = 'New Title'
book.genre = 'Fiction'
println book.dirtyPropertyNames    // ['title', 'genre']
----
