datasources:
  default:
    # Define the following for local development
    #url: 'jdbc:postgresql://localhost/cli-analytics'
    #username: 'postgres'
    #password: 'secret'
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
grails:
  forge:
    analytics:
      caller-subject: ${GRAILS_FORGE_ANALYTICS_CALLER_SUBJECT}
micronaut:
  security:
    authentication: bearer
    redirect:
      enabled: false
    token:
      jwt:
        claims-validators:
          issuer: https://accounts.google.com
          audience: ${GRAILS_FORGE_ANALYTICS_AUDIENCE}
        signatures:
          jwks:
            google:
              url: https://www.googleapis.com/oauth2/v3/certs
---
flyway:
  enabled: enabled
  datasources:
    default:
      locations: classpath:databasemigrations
